services:
  nginx-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-frontend
    ports:
      - "8080:8080"
      - "443:443"
    networks:
      - transcendence_nw
    secrets:
      - nginx_server_crt
      - nginx_server_key
    depends_on:
      - nodejs-backend

secrets:
  nginx_server_crt:
    file: ${SECRETS_FOLDER_RELATIVE_PATH}/nginx_server_crt.txt
  nginx_server_key:
    file: ${SECRETS_FOLDER_RELATIVE_PATH}/nginx_server_key.txt
