services:
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    container_name: nginx-prometheus-exporter
    restart: unless-stopped
    ports:
      - "9113:9113"
    command:
      - '--nginx.scrape-uri=http://nginx-frontend:8082/stub_status'
    depends_on:
      - nginx-frontend
    networks:
      - transcendence_nw

#port 9113
