groups:
- name: container.rules
  interval: 15s
  rules:
  - record: container_alive
    expr: max by (name) ((max(container_start_time_seconds{name!=""}) by (name) * 0 + 1) OR on(name)(container_should_exist * 0))
