global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml"
  - "container_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: cadvisor
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node-exporter
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 172.17.0.1:9100

  - job_name: nodejs-backend
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - nodejs-backend:3000