services:
  alertmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alertmanager
    restart: on-failure
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--log.format=json"
      - "--log.level=info"
    volumes:
      - alertmanager-data:/alertmanager
      - alertmanager-vault-secrets:/vault/secrets:ro
    depends_on:
      vault-agent-alertmanager:
        condition: service_healthy
    networks:
      - transcendence_nw

volumes:
  alertmanager-data: