services:
  vault-agent-nodejs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault-agent-nodejs-backend
    restart: on-failure
    cap_add:
      - IPC_LOCK
    environment:
      - SKIP_SETCAP=true
      - VAULT_LOG_FORMAT=json
      - VAULT_LOG_LEVEL=info
    volumes:
      - vault-agent-nodejs-backend-data:/vault/file
      - vault-agent-nodejs-backend-logs:/vault/logs
      - vault-agent-nodejs-backend-id:/vault/approle
      - nodejs-backend-vault-secrets:/vault/secrets:rw
    command: ["vault", "agent", "-config=/vault/config/agent.hcl"]
    networks:
      - transcendence_nw
    healthcheck:
      test: 
        - "CMD-SHELL"
        - |
          test -f /vault/secrets/google_auth_client_id && \
          test -f /vault/secrets/google_auth_secret_id && \
          test -f /vault/secrets/ws_secret && \
          test -f /vault/secrets/jwt_secret
      interval: 3s
      retries: 12
#port 8200

volumes:
  vault-agent-nodejs-backend-data:
  vault-agent-nodejs-backend-logs: