services:
  nodejs-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-backend
    restart: unless-stopped
    volumes:
      - nodejs-backend-data:/app/data
      - nodejs-backend-uploads:/app/uploads
    networks:
      - transcendence_nw

volumes:
  nodejs-backend-data:
  nodejs-backend-uploads: