services:
  alertmanager:
    build:
      context: .
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - 9093
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      - transcendence_nw