services:
  vault-agent-kibana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault-agent-kibana
    restart: on-failure
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-agent-kibana-data:/vault/file
      - vault-agent-kibana-logs:/vault/logs
      - vault-agent-kibana-id:/vault/approle
      - kibana-vault-secrets:/vault/secrets:rw
    command: ["vault", "agent", "-config=/vault/config/agent.hcl"]
    networks:
      - transcendence_nw
    healthcheck:
      test: 
        - "CMD-SHELL"
        - |
          test -f /vault/secrets/kibana.crt && \
          test -f /vault/secrets/kibana.key && \
          test -f /vault/secrets/ca.crt && \
          test -f /vault/secrets/kibana_encryption_key && \
          test -f /vault/secrets/kibana_system_password
      interval: 3s
      retries: 12
#port 8200

volumes:
  vault-agent-kibana-data:
  vault-agent-kibana-logs: