services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elasticsearch
    restart: on-failure
    cap_add:
      - IPC_LOCK
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-config:/usr/share/elasticsearch/config
      - elasticsearch-vault-secrets:/usr/share/elasticsearch/config/secrets:ro
    ports:
      - "9200:9200"
    depends_on:
      vault-agent-elasticsearch:
        condition: service_healthy
    healthcheck:
      test: test -f /usr/share/elasticsearch/.healthy
      interval: 10s
      retries: 30
    networks:
      - transcendence_nw

volumes:
  elasticsearch-data:
  elasticsearch-config:

#port 9200